# Generated by Django 5.0.7 on 2024-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_client_phone_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
